MODEL:
  TYPE: vit_ldm
  NAME: dmim_pretrain
  DROP_PATH_RATE: 0.1
  VIT:
    EMBED_DIM: 768
    DEPTH: 12
    NUM_HEADS: 12
    USE_APE: False
    USE_RPB: False
    USE_SHARED_RPB: True
    USE_MEAN_POOLING: False
  DIFFUSION:
    MODEL_CHANNELS: 256
    TIMESTEPS: 1000
    GIVEN_BETAS: None
DATA:
  IMG_SIZE: 224
  MASK_PATCH_SIZE: 32
  MASK_RATIO: 0.6
TRAIN:
  EPOCHS: 100
  WARMUP_EPOCHS: 5
  BASE_LR: 1e-4
  WARMUP_LR: 5e-7
  WEIGHT_DECAY: 0.05
  LR_SCHEDULER:
    NAME: 'cosine'
PRINT_FREQ: 10
SAVE_FREQ: 1
TAG: dmim_pretrain__vit_base__img224__100ep
